# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Davide Posillipo Webpage
description: >- # this means to ignore newlines until "baseurl:"
  Personal webpage of Davide Posillipo
baseurl: "" # the subpath of the site
url: "https://davideposillipo.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpeg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Interests
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: dposillipo@outlook.com
      link: mailto:dposillipo@outlook.com
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/davide-posillipo/
    - name: GitHub
      link: https://github.com/DavidePosillipo
    - name: Instagram
      link: https://www.instagram.com/dav_posillipo/
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
